services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: minhasenha123
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U keycloak_user -d keycloak",
        ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network
    ports:
      - "5432:5432"

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.render
    env_file:
      - env.render.local
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./themes/:/opt/keycloak/themes/
    networks:
      - keycloak_network

volumes:
  postgres_data:

networks:
  keycloak_network:
    driver: bridge

