services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${KC_DB_URL_DATABASE}
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${KC_DB_USERNAME} -d ${KC_DB_URL_DATABASE}",
        ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network
    ports:
      - "5432:5432"

  keycloak:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - "${KC_HTTP_PORT}:8080"
      - "${KC_HTTPS_PORT}:8443"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config/themes/:/opt/keycloak/themes/
    networks:
      - keycloak_network

volumes:
  postgres_data:

networks:
  keycloak_network:
    driver: bridge
