services:
  - type: web
    name: keycloak
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health/ready
    envVars:
      # Credenciais de Admin
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        generateValue: true
      
      # Configuração do Banco de Dados (CORRIGIDO)
      - key: KC_DB
        value: postgres
      - key: KC_DB_URL_HOST
        fromDatabase:
          name: keycloak-db
          property: host
      - key: KC_DB_URL_PORT
        fromDatabase:
          name: keycloak-db
          property: port
      - key: KC_DB_URL_DATABASE
        fromDatabase:
          name: keycloak-db
          property: database
      - key: KC_DB_USERNAME
        fromDatabase:
          name: keycloak-db
          property: user
      - key: KC_DB_PASSWORD
        fromDatabase:
          name: keycloak-db
          property: password
      
      # Configuração de Rede e Proxy
      - key: KC_PROXY_HEADERS
        value: xforwarded
      - key: KC_HOSTNAME_STRICT
        value: "false"
      - key: KC_HTTP_ENABLED
        value: "true"
      
      # Configuração de Porta 
      - key: KC_HTTP_PORT
        value: "8080"
      - key: PORT
        value: "8080"
      
      # Health checks e métricas
      - key: KC_HEALTH_ENABLED
        value: "true"
      - key: KC_METRICS_ENABLED
        value: "true"
      
      # Configuração de Log
      - key: KC_LOG_LEVEL
        value: INFO

databases:
  - name: keycloak-db
    plan: free
    region: oregon
    databaseName: keycloak
    user: keycloak_user
